version: '3.1'

services:
  java:
    build: .

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5433:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 5555:5555